export * from "./contactUs";
export * from "./home";
export * from "./order";
export * from "./orderList";
export * from "./privacypolicy";
export * from "./products";
export * from "./returnpolicy";
export * from "./termsandcondition";
export * from "./skin-test";
