export * from "./aboutUs";
export * from "./axios";
export * from "./config";
export * from "./contactUs";
export * from "./home";
export * from "./orderList";
export * from "./orderPost";
export * from "./privacyPolicy";
export * from "./products";
export * from "./returnPolicy";
export * from "./resentOtp";
export * from "./termsAndCondition";
export * from "./user";
export * from "./featureCategory";
export * from "./featureBrands";
export * from "./saaf"
export * from "./qualityCompliance"
export * from "./navMenu";
export * from "./skin-test"
export * from "./skin-type"

